runtime/stats.go
Config mapstructure to use json tags for decoding to properly match CSV
field names.
This fixes fields such as Hrsp2xx that were not populated.
=> Fix stats mapstructure decoding

runtime/runtime_single_client.go
The client native was looping over the output on the master socket
expecting an EOF to break out of the for loop. The master socket does
not send this EOF unless a "quit" is appended to force a disconnect.
Without sending this "quit" any Runtime API commands that are sent will
just hang until a timeout is reached at which point they will output the
below error:
[
{
"error": "timeout reached",
"runtimeAPI": "/tmp/master.sock"
}
]
This commit appends a ";quit" command to all commands sent to the master
socket causing the master socket to send an EOF as expected.
=> BUG/MEDIUM: runtime: Add quit to commands sent to master socket

configuration/configuration.go
Currently when setting "stats_enable" to true it is adding the
line "stats enabled" to the haproxy config. This should really be
"stats enable". This patch fixes #36.
=> BUG/MINOR: frontend: Fix stats enable directive

configuration/configuration.go
When attempting to update the value of http-reuse within the defaults
section a panic reflect error is encountered:
Panic reflect: call of reflect.Value.Elem on string Value:
client-native/configuration/configuration.go:1450 setFieldValue
This commit fix #33 by removing the Elem() call on field and replacing
with just String().
=> BUG/MEDIUM: defaults: Fix panic reflect for http-reuse

configuration/service.go
To avoid sending traffic to unhealthy servers that are found using service discovery health checks should be enabled.
=> MINOR: service: Enable health checks

go.mod, go.sum, runtime/acls.go, runtime/acls_test.go, runtime/haproxy_mock.go
Hi haproxy maintainers,
I played around with your cool runtime client and I noticed that currently it is not possible to add acl entires to a file which we need to maintain dynamically.
Therefore I created `acls.go` similar to `maps.go`. So it's possible to execute followed commands:
```
show acl
show acl %s
get acl #%s %s
add acl #%s %s
del acl #%s %s
```
It seems the [models/alc.go](https://github.com/haproxytech/models/blob/ea0dd4a520f93b8617fab64379f9dd68f6ef9af5/acl.go) is created for the configuration and not for the runtime. I created new local types. In case you are interested for this PR I can also create a PR to add these types to the model repo.
I look forward to your feedback.
Regards,
Thomas
PS: I also noticed that there are no tests for the runtime. So I tested the …
=> FEATURE/MINOR: runtime: add acl support

configuration/bind.go, configuration/bind_test.go
The `ssl-min-ver` bind option is incorrectly serialized. This change fixes the issue.
=> BUG/MEDIUM: bind: fix ssl-min-ver serialization

.github/workflows/test.yml
Providing e2e test suite using GitHub Actions.
The actual strategy matrix provides support for HAProxy 2.1, 2.2, and 2.3.
=> BUILD/MINOR: github: adding e2e action

runtime/runtime_single_client.go
Some of our servers are experiencing file descriptor exhaustion that we traced to the code that handles socket operations. While we don't know yet why haproxy's stats socket misbehaved, this now makes sure that these errors are properly handled by client-native.
* Ensure connections are closed in case of error 
* Set timeout to socket operations
=> BUG/MEDIUM: unix socket error handling

misc/stringutil.go
When generating SRV names for service discovery mechanisms it's
very likely that multiple backends will end up with similar server
names. Even removing a backend and having it re-added will frequently
produce similar names that it had before removing it. The rand library
docs state that:
"Top-level functions, such as Float64 and Int, use a
default shared Source that produces a deterministic sequence of values
each time a program is run. Use the Seed function to initialize the
default Source if different behavior is required for each run."
This patch adds a rand.Seed() to prevent the same names from being used
in different backends.
This fixes #66
=> BUG/MINOR: Add rand.Seed() to RandomString()

configuration/tcp_request_rule.go, configuration/tcp_request_rule_test.go
Follow up on https://github.com/haproxytech/client-native/pull/70
It appears that there are no tests to cover the https://github.com/haproxytech/client-native/blob/b1d1624dea70be1e352d3c32c5a8ee3bc3dbbfa0/configuration/tcp_request_rule.go#L439 function and I missed adding the `SilentDrop` action there
=> BUG/MEDIUM: config: Fix tcp-request connection silent-drop parsing

configuration/configuration_test.go, configuration/http_request_rule.go, configuration/http_request_rule_test.go
Redirect code is an optional argument. If it is not declared in the config file, `ParseHTTPRequestRule` will return an ErrSyntax from `strconv.ParseInt`.
=> BUG/MEDIUM: config: Fix http-request-rule redirect code parsing

configuration/configuration_test.go, configuration/http_request_rule.go, configuration/http_request_rule_test.go
As documentation says ``deny_status`` for ``deny`` and ``tarpit`` ``http-request`` actions is optional, this PR makes it really optional and fixes bug described in #77.
=> BUG/MINOR: make deny_status for http-request deny and tarpit optional

configuration/server.go
Currently, if a server is created and `CheckSendProxy` is `enabled` then `check-send-proxy` appears twice:
```
backend test
...
server testserver localhost:1337 check-send-proxy check-send-proxy send-proxy-v2
```
This seems to be a copy paste mistake.
=> Fix duplicate check-send-proxy option

configuration/bind.go, configuration/bind_test.go
There was a space in the name of a few parameters for binds that prevented the parsing of them back out of the configuration file. This was seen while using the Dataplane API. I've added these cases to the tests.
=> BUG/MINOR: Remove erroneous space preventing parse of some bind params

.github/workflows/actions.yml, runtime/haproxy_mock.go
This project should have race detector enabled in CI. 
There was a real data race in HAProxy mock that was fixed as well. Somewhat harmless today, but not enabling race detector can lead to unexpected problems in future.
Example of a race condition is available in commit: https://github.com/haproxytech/client-native/pull/96/commits/e9538cda1b8e21a172644671f71078d687ef9db2
=> Enable race detection for CI and fix race bug

.github/workflows/actions.yml
This should fix partially the broken CI on GitHub.
=> BUG/MINOR: ci: removing deprecated make target

configuration/configuration.go
When parsing a backend with the balance option set to `uri path-only`, the parameter `PathOnly` is ignored:
```go
func TestBalance(t *testing.T) {
configFile, _ := os.CreateTemp("/tmp", "")
_, _ = configFile.WriteString(`
backend app
balance uri path-only
`)
config, _ := configuration.New(
context.Background(),
options.ConfigurationFile(configFile.Name()),
options.HAProxyBin("echo"),
options.TransactionsDir("/tmp"),
)
_, backend, _ := config.GetBackend("app", "")
assert.True(t, backend.Balance.URIPathOnly)
}
```
=> BUG/MINOR: add missing field when parsing backend `balance` field

configuration/configuration.go
```
fatal error: concurrent map writes
goroutine 18653 [running]:
github.com/haproxytech/client-native/v5/configuration.(*client).DeleteParser(0xc003a72000, {0xc00211f830, 0x24})
/home/runner/go/pkg/mod/github.com/haproxytech/client-native/v5@v5.0.2/configuration/configuration.go:155 +0x18f
github.com/haproxytech/client-native/v5/configuration.(*Transaction).DeleteTransaction(0xc003a72000, {0xc00211f830, 0x24})
/home/runner/go/pkg/mod/github.com/haproxytech/client-native/v5@v5.0.2/configuration/transaction.go:438 +0x12e
github.com/haproxytech/client-native/v5/configuration.(*Transaction).ErrAndDeleteTransaction(...)
/home/runner/go/pkg/mod/github.com/haproxytech/client-native/v5@v5.0.2/configuration/transaction.go:729
github.com/haproxytech/client-native/v5/configuration.(*Transaction).Han …
```
=> BUG/MEDIUM: parser: fix: concurrent map writes

runtime/counters.go, runtime/interface.go, runtime/runtime_client.go
Adds ClearCounters() and ClearCountersAll() to reset counters.
I omitted models and tests as the socket command seems to never return any data.
This closes #111
=> MINOR: Add ClearCounters() and ClearCountersAll()

config-parser/parsers/http/actions/return.go
Hey, team.
I've added a valid status code to the allowedErrorCodes map for proxy authentication as the program just removes the deny_status attribute in the configuration file otherwise.
Thank you.
=> allowedErrorCodes: adds '407 Proxy Authentication Required'.

models/stick_table.go, models/stick_table_entry.go, models/stick_table_entry_compare.go, models/stick_table_entry_compare_test.go, runtime/stick_tables.go, specification/build/haproxy_spec.yaml, specification/models/runtime/table.yaml, specification/models/runtime/table_entry.yaml
HAProxy recently added a new sticktable counter for "glitches". This PR adds support for those to the library.
If any changes are desired for inclusions in upstream (in particular in regards to style), I am happy to apply them
=> MEDIUM: runtime: Add glitch metrics to stick table fields

specification/build/haproxy_spec.yaml
Based on Feedback in https://github.com/haproxytech/dataplaneapi/issues/365 there should be no reason why Creating a certificate can't skip a reload.
=> MINOR: Add option to skip a reload, when creating a SSL Certificate

configuration/global.go
Parse tune.bufsize as a number. Buffer size needs to be in bytes.
=> BUG/MINOR: tune.bufsize parse as a number

go.mod, go.sum, runtime/stats.go
Replace module [`github.com/mitchellh/mapstructure`](https://pkg.go.dev/github.com/mitchellh/mapstructure) with [`github.com/go-viper/mapstructure/v2`](https://pkg.go.dev/github.com/go-viper/mapstructure/v2).
Note: github.com/mitchellh/mapstructure is still referenced in dependencies of go-openapi packages, but this is already being fixed (see https://github.com/go-openapi/strfmt/pull/157 ) and will be released with the next `github.com/go-openapi/strfmt` release.
Module [`github.com/mitchellh/mapstructure`](https://pkg.go.dev/github.com/mitchellh/mapstructure) isn't supported anymore and the repository has been archived. Announcement: https://gist.github.com/mitchellh/90029601268e59a29e64e55bab1c5bdc The blessed fork is at [`github.com/go-viper/mapstructure/v2`](https://pkg.go.dev/github. …
=> BUILD/MINOR: upgrade dependency mapstructure to supported fork

storage/cert-info.go
Extending the logic to check if both CommonName or SubjectAlternativeNames are not empty. This fixes the cases where names are too long and have no CN but only SAN.
cc https://github.com/haproxytech/client-native/issues/129
=> BUG/MINOR: cert-info: enhance leaf certificate selection to include SAN
